### ISSUE TITLE
Receiving Error "name 'wkt' is not defined"

### ISSUE THREAD

**Issue by keballantyne** [nrcan-eodms-sgdot-rncan/eodms-rapi-orderdownload#5]
Receiving the following error:

```
ERROR: 
Traceback (most recent call last):
  File "eodms-orderdownload.py", line 864, in main
    search_orderDownload(params)
  File "eodms-orderdownload.py", line 328, in search_orderDownload
    query_imgs = eodms_query.query_records()
  File "/emi/proc/rcm/eodms-rapi-orderdownload-main/utils/utils.py", line 1350, in query_records
    self.aoi_feats = eodms_geo.get_features()
  File "/emi/proc/rcm/eodms-rapi-orderdownload-main/utils/geo.py", line 332, in get_features
    wkt_feat = wkt.dumps(json_geom, decimals=3)
NameError: name 'wkt' is not defined
```

**Comment by keballantyne** [comment]
The 'wkt' variable is imported from the geomet Python package. Added an import statement for geomet to the geo.py script (also updated README to notify users they need to install the geomet package).
