### ISSUE TITLE
Issue with Order Key for Radarsat1 and NAPL

### ISSUE THREAD

**Issue by keballantyne** [nrcan-eodms-sgdot-rncan/eodms-rapi-orderdownload#7]
An error occurs when using a CSV file from the EODMS UI. The mapping for collections Radarsat1 and NAPL in the script does not include an ORDER_KEY so the following error occurs:

`ERROR:
Traceback (most recent call last):
  File "C:\Working\Development\EODMS\eodms-rapi-orderdownload\dev\eodms-orderdownload.py", line 893, in main
    order_download(params)
  File "C:\Working\Development\EODMS\eodms-rapi-orderdownload\dev\eodms-orderdownload.py", line 239, in order_download
    query_imgs = eodms_csv.import_eodmsCSV()
  File "C:\Working\Development\EODMS\eodms-rapi-orderdownload\dev\utils\csv_util.py", line 198, in import_eodmsCSV
    out_recs = query_obj.query_csvRecords(records)
  File "C:\Working\Development\EODMS\eodms-rapi-orderdownload\dev\utils\utils.py", line 1369, in query_csvRecords
    rapi_id = coll_filts['ORDER_KEY']
KeyError: 'ORDER_KEY'`

**Comment by keballantyne** [comment]
ORDER_KEY is now mapped properly.
